name: Task1
on: [push, workflow_dispatch]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Lint the project
        run: npm run lint
      - name: Output
        run: echo "Linting the project finished"
  Build:
    runs-on: ubuntu-latest
    needs: Lint
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Lint the project
        run: npm run build
      - name: Output
        run: echo "Building the project finished"
  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Lint the project
        run: npm run test
      - name: Output
        run: echo "Testing the project finished"

  Deploy:
    runs-on: ubuntu-latest
    needs: Test
    steps:
    - name: Output
      run: echo "Running deploy"
